apiVersion: velero.io/v1
kind: Backup
metadata:
  namespace: oadp-operator
  name: backup1
spec:
  includedNamespaces:
  - my-database-app
  excludedResources:
  - buildconfigs.build.openshift.io
  - imagetags.image.openshift.io
  snapshotVolumes: false
